CREATE TABLE ALUNO (
	ID SERIAL,
	NOME VARCHAR(255),
	CPF CHAR(11),
	OBSERVACAO TEXT,
	IDADE INTEGER,
	DINEHIRO NUMERIC(10, 2),
	ALTURA REAL,
	ATIVO BOOLEAN,
	DATA_NASCIMENTO DATE,
	HORA_AULA TIME,
	MATRICULADO_EM TIMESTAMP
);

SELECT
	*
FROM
	ALUNO;

ALTER TABLE ALUNO RENAME COLUMN DINEHIRO TO DINHEIRO;

-- Corrigigindo a coluna dinehiro